// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastService(arg1, arg2) {
  return window['go']['discovery']['DiscoveryService']['BroadcastService'](arg1, arg2);
}

export function GetPeer(arg1) {
  return window['go']['discovery']['DiscoveryService']['GetPeer'](arg1);
}

export function GetPeers() {
  return window['go']['discovery']['DiscoveryService']['GetPeers']();
}

export function QueryService() {
  return window['go']['discovery']['DiscoveryService']['QueryService']();
}

export function RefreshQuery() {
  return window['go']['discovery']['DiscoveryService']['RefreshQuery']();
}

export function Startup(arg1) {
  return window['go']['discovery']['DiscoveryService']['Startup'](arg1);
}
