// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';
import {response} from '../models';
import {context} from '../models';

export function BroadcastService(arg1:string,arg2:string):Promise<void>;

export function GetPeer(arg1:string):Promise<discovery.PeerModel>;

export function GetPeers():Promise<response.Response___chat_client_internal_discovery_PeerModel_>;

export function QueryService():Promise<void>;

export function RefreshQuery():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
