// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {context} from '../models';

export function BroadcastService(arg1:string,arg2:string):Promise<void>;

export function GetPeers():Promise<response.Response___chat_client_internal_discovery_PeerModel_>;

export function QueryService(arg1:any):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
