// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProfile() {
  return window['go']['auth']['AuthService']['GetProfile']();
}

export function Register(arg1) {
  return window['go']['auth']['AuthService']['Register'](arg1);
}

export function Startup(arg1) {
  return window['go']['auth']['AuthService']['Startup'](arg1);
}
