// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {context} from '../models';

export function GetProfile():Promise<auth.UserModel>;

export function Register(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
