// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {user} from '../models';
import {discovery} from '../models';
import {context} from '../models';

export function GetProfile():Promise<response.Response_chat_client_internal_user_UserProfile_>;

export function Login(arg1:string,arg2:string):Promise<response.Response_chat_client_internal_user_UserProfile_>;

export function PairUser(arg1:user.RequestPairSchema):Promise<user.ResponsePairSchema>;

export function Register(arg1:string,arg2:string):Promise<response.Response_chat_client_internal_user_UserProfile_>;

export function RequestPair(arg1:discovery.PeerModel):Promise<response.Response_string_>;

export function Startup(arg1:context.Context):Promise<void>;
