// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {user} from '../models';
import {context} from '../models';

export function GeneratePairingCode():Promise<response.Response_string_>;

export function GetContacts():Promise<response.Response___chat_client_internal_user_ContactModel_>;

export function GetProfile():Promise<response.Response_chat_client_internal_user_UserProfile_>;

export function HandleUserPairing(arg1:user.InitPairSchema):Promise<user.ResponsePairSchema>;

export function Login(arg1:string,arg2:string):Promise<response.Response_chat_client_internal_user_UserProfile_>;

export function Register(arg1:string,arg2:string):Promise<response.Response_chat_client_internal_user_UserProfile_>;

export function RequestPairing(arg1:user.RequestPairSchema):Promise<response.Response_string_>;

export function ScanPeers():Promise<response.Response___chat_client_internal_discovery_PeerModel_>;

export function Startup(arg1:context.Context):Promise<void>;
