// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePairingCode() {
  return window['go']['user']['UserService']['GeneratePairingCode']();
}

export function GetContacts() {
  return window['go']['user']['UserService']['GetContacts']();
}

export function GetProfile() {
  return window['go']['user']['UserService']['GetProfile']();
}

export function HandleUserPairing(arg1) {
  return window['go']['user']['UserService']['HandleUserPairing'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['user']['UserService']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['user']['UserService']['Register'](arg1, arg2);
}

export function RequestPairing(arg1) {
  return window['go']['user']['UserService']['RequestPairing'](arg1);
}

export function ScanPeers() {
  return window['go']['user']['UserService']['ScanPeers']();
}

export function Startup(arg1) {
  return window['go']['user']['UserService']['Startup'](arg1);
}
