// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultUser() {
  return window['go']['user']['UserService']['GetDefaultUser']();
}

export function GetProfile() {
  return window['go']['user']['UserService']['GetProfile']();
}

export function Login(arg1, arg2) {
  return window['go']['user']['UserService']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['user']['UserService']['Register'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['user']['UserService']['Startup'](arg1);
}
