// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';
import {response} from '../models';
import {context} from '../models';

export function GetRooms():Promise<Array<chat.ChatRoom>>;

export function SendMessage(arg1:chat.ChatRoom,arg2:chat.ChatMessage):Promise<response.Response>;

export function ServeChat():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
