// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {chat} from '../models';
import {context} from '../models';

export function GetRooms():Promise<response.Response___chat_client_internal_chat_ChatRoom_>;

export function SendMessage(arg1:chat.ChatRoom,arg2:chat.ChatMessage):Promise<response.Response_string_>;

export function ServeChat():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
