// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1) {
  return window['go']['chat']['ChatService']['CreateChat'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['chat']['ChatService']['GetMessages'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['chat']['ChatService']['SendMessage'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['chat']['ChatService']['Startup'](arg1);
}
