// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';
import {response} from '../models';
import {user} from '../models';
import {context} from '../models';

export function CreateChat(arg1:chat.SendMessageSchema):Promise<void>;

export function GetMessages(arg1:string,arg2:number):Promise<response.Response___chat_client_internal_chat_ChatMessage_>;

export function SendMessage(arg1:user.ContactModel,arg2:chat.SendMessageSchema):Promise<response.Response_chat_client_internal_chat_ChatMessage_>;

export function Startup(arg1:context.Context):Promise<void>;
